### ISSUE TITLE
Air quality Api

### ISSUE THREAD

**Issue by supspe666** [m0rp43us/openmeteopy#9]
Traceback (most recent call last):
  File "//openmeteopy/test.py", line 14, in <module>
    mgr = OWmanager(options,OWmanager.air_quality,hourly.all())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openmeteopy/openmeteo_py/OWmanager.py", line 280, in __init__
    self.payload['hourly'] = ','.join(self.hourly.hourly_params)
    ^^^^^^^^^^^^
AttributeError: 'OWmanager' object has no attribute 'payload'

**Comment by m0rp43us** [comment]
issue fixed
